<?php

/**
 * This file is part of the OpenPNE package.
 * (c) OpenPNE Project (http://www.openpne.jp/)
 *
 * For the full copyright and license information, please view the LICENSE
 * file and the NOTICE file that were distributed with this source code.
 */

/**
 * PluginApplicationInvite
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    opOpenSocialPlugin
 * @subpackage model
 * @author     Shogo Kawahara <kawahara@tejimaya.net>
 */
abstract class PluginApplicationInvite extends BaseApplicationInvite
{
 /**
  * accept this invitation
  *
  * @return MemberApplication $memberApplication
  */
  public function accept()
  {
    return $this->getApplication()->addToMember($this->getToMember(), array(
      'is_view_home' => true,
      'is_view_profile' => true
    ), array(
      'invite' => $this->getFromMemberId()
    ));
  }
}
