<?php

/**
 * This file is part of the OpenPNE package.
 * (c) OpenPNE Project (http://www.openpne.jp/)
 *
 * For the full copyright and license information, please view the LICENSE
 * file and the NOTICE file that were distributed with this source code.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class opOpenSocialPlugin9_createIndex extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('application_invite', 'application_invite_application_id_application_id', array(
      'name' => 'application_invite_application_id_application_id',
      'local' => 'application_id',
      'foreign' => 'id',
      'foreignTable' => 'application',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
      ));
    $this->createForeignKey('application_invite', 'application_invite_to_member_id_member_id', array(
      'name' => 'application_invite_to_member_id_member_id',
      'local' => 'to_member_id',
      'foreign' => 'id',
      'foreignTable' => 'member',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
      ));
    $this->createForeignKey('application_invite', 'application_invite_from_member_id_member_id', array(
      'name' => 'application_invite_from_member_id_member_id',
      'local' => 'from_member_id',
      'foreign' => 'id',
      'foreignTable' => 'member',
      'onUpdate' => '',
      'onDelete' => 'CASCADE',
      ));
    $this->addIndex('application_invite', 'application_invite_application_id', array(
      'fields' => 
      array(
       0 => 'application_id',
      ),
      ));
    $this->addIndex('application_invite', 'application_invite_to_member_id', array(
      'fields' => 
      array(
       0 => 'to_member_id',
      ),
      ));
    $this->addIndex('application_invite', 'application_invite_from_member_id', array(
      'fields' => 
      array(
       0 => 'from_member_id',
      ),
      ));
  }

  public function down()
  {
    $this->dropForeignKey('application_invite', 'application_invite_application_id_application_id');
    $this->dropForeignKey('application_invite', 'application_invite_to_member_id_member_id');
    $this->dropForeignKey('application_invite', 'application_invite_from_member_id_member_id');
    $this->removeIndex('application_invite', 'application_invite_application_id', array(
      'fields' => 
      array(
       0 => 'application_id',
      ),
      ));
    $this->removeIndex('application_invite', 'application_invite_to_member_id', array(
      'fields' => 
      array(
       0 => 'to_member_id',
      ),
      ));
    $this->removeIndex('application_invite', 'application_invite_from_member_id', array(
      'fields' => 
      array(
       0 => 'from_member_id',
      ),
      ));
  }
}
