<?php

/**
 * This file is part of the OpenPNE package.
 * (c) OpenPNE Project (http://www.openpne.jp/)
 *
 * For the full copyright and license information, please view the LICENSE
 * file and the NOTICE file that were distributed with this source code.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class opOpenSocialPlugin10_addColumnToApplicationTable extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('application', 'consumer_key', 'string', '16', array(
         'default' => '',
         'notnull' => '1',
       ));
    $this->addColumn('application', 'consumer_secret', 'string', '32', array(
         'default' => '',
         'notnull' => '1',
         ));
  }

  public function down()
  {
    $this->removeColumn('application', 'consumer_key');
    $this->removeColumn('application', 'consumer_secret');
  }
}
