<?php

/**
 * This file is part of the OpenPNE package.
 * (c) OpenPNE Project (http://www.openpne.jp/)
 *
 * For the full copyright and license information, please view the LICENSE
 * file and the NOTICE file that were distributed with this source code.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class opOpenSocialPlugin15_addColumnsToApplication extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('application', 'is_pc', 'boolean', '25', array(
      'notnull' => '1',
      'default' => '1',
    ));
    $this->addColumn('application', 'is_mobile', 'boolean', '25', array(
      'notnull' => '1',
      'default' => '0',
    ));
  }

  public function down()
  {
    $this->removeColumn('application', 'is_pc');
    $this->removeColumn('application', 'is_mobile');
  }
}

