<?php

/**
 * This file is part of the OpenPNE package.
 * (c) OpenPNE Project (http://www.openpne.jp/)
 *
 * For the full copyright and license information, please view the LICENSE
 * file and the NOTICE file that were distributed with this source code.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class opOpenSocialPlugin16_changeForeignTableOfActivity extends Doctrine_Migration_Base
{
  public function up()
  {
    $conn = Doctrine::getTable('ActivityData')->getConnection();
    $sql = 'SELECT id, foreign_table, foreign_id'
      . ' FROM '.Doctrine::getTable('ActivityData')->getTableName()
      . ' WHERE foreign_table = ?';
    $stmt = $conn->execute($sql, array(Doctrine::getTable('MemberApplication')->getTableName()));
    while ($r = $stmt->fetch(Doctrine::FETCH_ASSOC))
    {
      $ad = Doctrine::getTable('ActivityData')->find($r['id']);
      $ma = Doctrine::getTable('MemberApplication')->find($r['foreign_id']);
      if ($ad && $ma)
      {
        $ad->foreign_table = Doctrine::getTable('Application')->getTableName();
        $ad->foreign_id    = $ma->application_id;
        $ad->save();
      }
      if ($ad)
      {
        $ad->free();
      }
      if ($ma)
      {
        $ma->free();
      }
    }
  }
}
